<template>
  <div class="row">
    <div class="col-8 offset-2">
      <b-card bg-variant="light" class="mt-5">
        <b-card-body>
          <div class="h5 text-center mb-0">User Login</div>
          <hr class="mt-2" />
          <b-alert v-model="showMessage" variant="danger" dismissible>
            <strong>Authentication failed</strong> Please check your username and password and retry.
          </b-alert>
          <div class="row">
            <div class="col-8 offset-2">
              <form role="form" @submit="signIn">
                <b-form-group>
                  <b-form-input id="home-input-username" placeholder="Username or email address" />
                </b-form-group>
                <b-form-group>
                  <b-form-input type="password" id="home-input-password" required placeholder="Password" />
                </b-form-group>
                <b-button type="submit" variant="success">Submit</b-button>
              </form>
            </div>
          </div>
        </b-card-body>
      </b-card>
    </div>
  </div>
</template>

<script>
import { Meteor } from 'meteor/meteor';
import { Accounts } from 'meteor/accounts-base';

export default {
  data: function() {
    return {
      showMessage: false
    };
  },
  methods: {
    signIn(evt) {
      evt.preventDefault();
      this.showMessage = false; // in case it was previously true
      const username = $('#home-input-username').val();
      const passwd = $('#home-input-password').val();
      let _this = this;
      // FIXME: The error generated by this method for a failed login seems to make the page reload!
      Meteor.loginWithPassword(username, passwd, function(error) {
        if (error) {
          _this.showMessage = true;
          return false;
        } else {
          $('#home-input-username').val('');
          $('#home-input-password').val('');
        }
      });
    }
  }
}
</script>
